<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [

            [
                'group_name' => 'user-management',
                'permissions' => [
                    'role-list',
                    'role-create',
                    'role-edit',
                    'role-delete',
                    'user-list',
                    'user-create',
                    'user-edit',
                    'user-delete',
                ]
            ],
            [
                'group_name' => 'counsel-or-lawyer',
                'permissions' => [
                    'counsel-list',
                    'counsel-add',
                    'counsel-edit',
                    'counsel-delete',
                    'chamber-staff-list',
                    'chamber-staff-add',
                    'chamber-staff-edit',
                    'chamber-staff-delete',
                    'chamber-list',
                    'chamber-add',
                    'chamber-edit',
                    'chamber-delete',
                    'internal-counsel-list',
                    'internal-counsel-add',
                    'internal-counsel-edit',
                    'internal-counsel-delete',
                ]
            ],
            [
                'group_name' => 'admin-setup',
                'permissions' => [
                    'accused-list',
                    'accused-create',
                    'accused-edit',
                    'accused-delete',
                    'allegation-claim-list',
                    'allegation-claim-create',
                    'allegation-claim-edit',
                    'allegation-claim-delete',
                    'area-list',
                    'area-create',
                    'area-edit',
                    'area-delete',
                    'bank-list',
                    'bank-create',
                    'bank-edit',
                    'bank-delete',
                    'bank-branch-list',
                    'bank-branch-create',
                    'bank-branch-edit',
                    'bank-branch-delete',
                    'bill-type-list',
                    'bill-type-create',
                    'bill-type-edit',
                    'bill-type-delete',
                    'bill-particulars-list',
                    'bill-particulars-create',
                    'bill-particulars-edit',
                    'bill-particulars-delete',
                    'bill-schedules-list',
                    'bill-schedules-create',
                    'bill-schedules-edit',
                    'bill-schedules-delete',
                    'branch-list',
                    'branch-create',
                    'branch-edit',
                    'branch-delete',
                    'cabinet-list',
                    'cabinet-create',
                    'cabinet-edit',
                    'cabinet-delete',
                    'case-status-list',
                    'case-status-create',
                    'case-status-edit',
                    'case-status-delete',
                    'case-title-list',
                    'case-title-create',
                    'case-title-edit',
                    'case-title-delete',
                    'case-category-list',
                    'case-category-create',
                    'case-category-edit',
                    'case-category-delete',
                    'case-matter-list',
                    'case-matter-create',
                    'case-matter-edit',
                    'case-matter-delete',
                    'case-type-list',
                    'case-type-create',
                    'case-type-edit',
                    'case-type-delete',
                    'client-group-list',
                    'client-group-create',
                    'client-group-edit',
                    'client-group-delete',
                    'client-name-list',
                    'client-name-create',
                    'client-name-edit',
                    'client-name-delete',
                    'client-which-party-list',
                    'client-which-party-create',
                    'client-which-party-edit',
                    'client-which-party-delete',
                    'complainant-list',
                    'complainant-create',
                    'complainant-edit',
                    'complainant-delete',
                    'coordinator-or-tadbirkar-list',
                    'coordinator-or-tadbirkar-create',
                    'coordinator-or-tadbirkar-edit',
                    'coordinator-or-tadbirkar-delete',
                    'court-name-list',
                    'court-name-create',
                    'court-name-edit',
                    'court-name-delete',
                    'court-order-list',
                    'court-order-create',
                    'court-order-edit',
                    'court-order-delete',
                    'court-proceeding-list',
                    'court-proceeding-create',
                    'court-proceeding-edit',
                    'court-proceeding-delete',
                    'day-notes-list',
                    'day-notes-create',
                    'day-notes-edit',
                    'day-notes-delete',
                    'designation-list',
                    'designation-create',
                    'designation-edit',
                    'designation-delete',
                    'documents-list',
                    'documents-create',
                    'documents-edit',
                    'documents-delete',
                    'documents-type-list',
                    'documents-type-create',
                    'documents-type-edit',
                    'documents-type-delete',
                    'external-council-list',
                    'external-council-create',
                    'external-council-edit',
                    'external-council-delete',
                    'internal-council-list',
                    'internal-council-create',
                    'internal-council-edit',
                    'internal-council-delete',
                    'in-favour-of-list',
                    'in-favour-of-create',
                    'in-favour-of-edit',
                    'in-favour-of-delete',
                    'law-list',
                    'law-create',
                    'law-edit',
                    'law-delete',
                    'legal-issue-list',
                    'legal-issue-create',
                    'legal-issue-edit',
                    'legal-issue-delete',
                    'legal-service-list',
                    'legal-service-create',
                    'legal-service-edit',
                    'legal-service-delete',
                    'mode-of-received-list',
                    'mode-of-received-create',
                    'mode-of-received-edit',
                    'mode-of-received-delete',
                    'next-date-fixed-for-list',
                    'next-date-fixed-for-create',
                    'next-date-fixed-for-edit',
                    'next-date-fixed-for-delete',
                    'next-day-presence-list',
                    'next-day-presence-create',
                    'next-day-presence-edit',
                    'next-day-presence-delete',
                    'opposition-which-party-list',
                    'opposition-which-party-create',
                    'opposition-which-party-edit',
                    'opposition-which-party-delete',
                    'particulars-list',
                    'particulars-create',
                    'particulars-edit',
                    'particulars-delete',
                    'party-category-list',
                    'party-category-create',
                    'party-category-edit',
                    'party-category-delete',
                    'party-subcategory-list',
                    'party-subcategory-create',
                    'party-subcategory-edit',
                    'party-subcategory-delete',
                    'payment-type-list',
                    'payment-type-create',
                    'payment-type-edit',
                    'payment-type-delete',
                    'payment-mode-list',
                    'payment-mode-create',
                    'payment-mode-edit',
                    'payment-mode-delete',
                    'profession-list',
                    'profession-create',
                    'profession-edit',
                    'profession-delete',
                    'program-list',
                    'program-create',
                    'program-edit',
                    'program-delete',
                    'progress-list',
                    'progress-create',
                    'progress-edit',
                    'progress-delete',
                    'referrer-list',
                    'referrer-create',
                    'referrer-edit',
                    'referrer-delete',
                    'section-list',
                    'section-create',
                    'section-edit',
                    'section-delete',
                    'title-list',
                    'title-create',
                    'title-edit',
                    'title-delete',
                    'zone-list',
                    'zone-create',
                    'zone-edit',
                    'zone-delete',
                    'division-list',
                    'division-create',
                    'division-edit',
                    'division-delete',
                    'district-list',
                    'district-create',
                    'district-edit',
                    'district-delete',
                    'thana-list',
                    'thana-create',
                    'thana-edit',
                    'thana-delete',
                    'floor-list',
                    'floor-create',
                    'floor-edit',
                    'floor-delete',
                    'flat-number-list',
                    'flat-number-create',
                    'flat-number-edit',
                    'flat-number-delete',
                    'property-type-list',
                    'property-type-create',
                    'property-type-edit',
                    'property-type-delete',
                    'seller-or-buyer-list',
                    'seller-or-buyer-create',
                    'seller-or-buyer-edit',
                    'seller-or-buyer-delete',
                    'compliance-category-list',
                    'compliance-category-create',
                    'compliance-category-edit',
                    'compliance-category-delete',
                    'compliance-type-list',
                    'compliance-type-create',
                    'compliance-type-edit',
                    'compliance-type-delete',
                    'company-type-list',
                    'company-type-create',
                    'company-type-edit',
                    'company-type-delete',
                    'company-list',
                    'company-create',
                    'company-edit',
                    'company-delete',
                ]
            ],


//            [
//                'group_name' => 'product',
//                'permissions' => [
//                    'product-list',
//                    'product-create',
//                    'product-edit',
//                    'product-delete',
//                ]
//            ],

//            'role-list',
//            'role-create',
//            'role-edit',
//            'role-delete',
//            'product-list',
//            'product-create',
//            'product-edit',
//            'product-delete',
//            'designations',
//            'add-designations',
//            'edit-designations',
//            'delete-designations'

        ];

//        foreach ($permissions as $permission) {
//            Permission::create(['name' => $permission]);
//        }


        for ($i = 0; $i<count($permissions); $i++){
            $permissionGroup = $permissions[$i]['group_name'];
            for ($j = 0; $j<count($permissions[$i]['permissions']); $j++){
                Permission::create(['name' => $permissions[$i]['permissions'][$j], 'group_name' => $permissionGroup]);
            }
        }


    }
}
